version: '3.8'

services:
  webserver:
    image: httpd:latest
    ports:
      - "80:80"  # Maps port 80 of the container to port 80 on the host
    volumes:
      - ./html:/usr/local/apache2/htdocs/  # Optional: Mounts a directory from your host to the container for custom web content
