name: Deploy Container to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}
        
    - name: SSH and Pull & Run Docker Container
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
          docker pull firasnoun/testing:v1
          docker stop my-container || true
          docker rm my-container || true
          docker run -d --name my-container firasnoun/testing:v1
        EOF
